-- Contact form submissions
create table contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  status text default 'new'::text
);

-- Booking slots
create table booking_slots (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  time time not null,
  name text,
  email text,
  status text default 'available'::text,
  meeting_type text
);

-- Add row level security
alter table contact_submissions enable row level security;
alter table booking_slots enable row level security; 