name: Sync Existing Issues

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  sync_existing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Project Info
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: project
        run: |
          # First get the project ID and field information
          echo "Getting project ID..."
          PROJECT_DATA=$(gh api graphql -f query='
            query {
              user(login: "weir1") {
                projectV2(number: 3) {
                  id
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                      ... on ProjectV2Field {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }')
          
          echo "Project data: $PROJECT_DATA"
          
          # Extract project ID
          PROJECT_ID=$(echo "$PROJECT_DATA" | jq -r '.data.user.projectV2.id')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "Found Project ID: $PROJECT_ID"
          
          # Get Priority field info including options
          PRIORITY_FIELD=$(echo "$PROJECT_DATA" | jq -r '.data.user.projectV2.fields.nodes[] | select(.name=="Priority")')
          echo "Priority field data: $PRIORITY_FIELD"
          
          PRIORITY_FIELD_ID=$(echo "$PRIORITY_FIELD" | jq -r '.id')
          echo "PRIORITY_FIELD_ID=$PRIORITY_FIELD_ID" >> $GITHUB_ENV
          echo "Found Priority Field ID: $PRIORITY_FIELD_ID"
          
          # Get priority options
          PRIORITY_OPTIONS=$(echo "$PRIORITY_FIELD" | jq -r '.options')
          echo "Priority options: $PRIORITY_OPTIONS"
          echo "PRIORITY_OPTIONS='$PRIORITY_OPTIONS'" >> $GITHUB_ENV
          
          # Get other field IDs
          DATE_FIELD_ID=$(echo "$PROJECT_DATA" | jq -r '.data.user.projectV2.fields.nodes[] | select(.name=="Due Date") | .id')
          echo "DATE_FIELD_ID=$DATE_FIELD_ID" >> $GITHUB_ENV
          echo "Found Date Field ID: $DATE_FIELD_ID"
      
      - name: Sync Existing Issues
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Get all issues
          issues=$(gh api -X GET /repos/${{ github.repository }}/issues \
            -F state=all \
            -F per_page=100)
          
          # For each issue
          echo "$issues" | jq -c '.[]' | while read -r issue; do
            issue_number=$(echo "$issue" | jq -r '.number')
            title=$(echo "$issue" | jq -r '.title')
            node_id=$(echo "$issue" | jq -r '.node_id')
            
            echo "Processing issue #$issue_number: $title"
            
            # Add to project
            ADD_RESPONSE=$(gh api graphql -f query='
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }' -f projectId="$PROJECT_ID" -f contentId="$node_id")
            
            item_id=$(echo "$ADD_RESPONSE" | jq -r '.data.addProjectV2ItemById.item.id')
            echo "Added to project, got item ID: $item_id"
            
            # Get labels
            labels=$(echo "$issue" | jq -r '.labels[].name // empty')
            
            # Set priority based on labels
            if echo "$labels" | grep -q "p0-critical"; then
              priority_name="P0 - Critical 🚨"
            elif echo "$labels" | grep -q "high-priority"; then
              priority_name="P1 - High Priority 🔥"
            elif echo "$labels" | grep -q "feature"; then
              priority_name="P2 - Important 📈"
            else
              priority_name="P3 - Normal ⭐"
            fi
            
            # Get option ID for the priority
            priority_option_id=$(echo "$PRIORITY_OPTIONS" | jq -r ".[] | select(.name==\"$priority_name\") | .id")
            echo "Found priority option ID: $priority_option_id for $priority_name"
            
            if [ ! -z "$priority_option_id" ]; then
              # Update priority
              echo "Setting priority to $priority_name with option ID $priority_option_id..."
              gh api graphql -f query='
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: $fieldId
                      value: { 
                        singleSelectOptionId: $optionId
                      }
                    }
                  ) {
                    projectV2Item {
                      id
                    }
                  }
                }' -f projectId="$PROJECT_ID" -f itemId="$item_id" -f fieldId="$PRIORITY_FIELD_ID" -f optionId="$priority_option_id"
            else
              echo "Warning: Could not find option ID for priority $priority_name"
            fi
            
            # Set due date (March 7, 2025)
            echo "Setting due date..."
            gh api graphql -f query='
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { 
                      date: "2025-03-07"
                    }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }' -f projectId="$PROJECT_ID" -f itemId="$item_id" -f fieldId="$DATE_FIELD_ID"
            
            echo "Completed processing issue #$issue_number"
          done